CREATE TABLE IF NOT EXISTS sequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_minutes INTEGER NOT NULL,
    level INTEGER NOT NULL,
    peak_pose_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    peak_pose_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS breathing_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_breathing_master_name_category UNIQUE (name, category)
);

CREATE TABLE IF NOT EXISTS sequence_breathing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL,
    breathing_master_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sequence_breathing_sequence
        FOREIGN KEY (sequence_id) REFERENCES sequences(id),
    CONSTRAINT fk_sequence_breathing_master
        FOREIGN KEY (breathing_master_id) REFERENCES breathing_master(id)
);

CREATE INDEX IF NOT EXISTS idx_sequence_breathing_sequence_id
    ON sequence_breathing(sequence_id, display_order);

CREATE TABLE IF NOT EXISTS warming_up_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ja VARCHAR(255) NOT NULL,
    name_sanskrit VARCHAR(255),
    category VARCHAR(50),
    standing_subcategory VARCHAR(50),
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_warming_up_master_name_ja UNIQUE (name_ja)
);

CREATE TABLE IF NOT EXISTS sequence_warming_up (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL,
    warming_up_master_id BIGINT,
    custom_name VARCHAR(255),
    sort_order INTEGER NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sequence_warming_up_sequence
        FOREIGN KEY (sequence_id) REFERENCES sequences(id),
    CONSTRAINT fk_sequence_warming_up_master
        FOREIGN KEY (warming_up_master_id) REFERENCES warming_up_master(id),
    CONSTRAINT chk_sequence_warming_up_source
        CHECK (
            (warming_up_master_id IS NOT NULL AND custom_name IS NULL)
            OR (warming_up_master_id IS NULL AND custom_name IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_warming_up_master_display_order
    ON warming_up_master(display_order, id);

ALTER TABLE warming_up_master
    ADD COLUMN IF NOT EXISTS category VARCHAR(50);

ALTER TABLE warming_up_master
    ADD COLUMN IF NOT EXISTS standing_subcategory VARCHAR(50);

-- Classification is maintained by application-side seeders.
-- Avoid coercing all historical records into standing, because that pollutes standing-only candidate lists.

CREATE INDEX IF NOT EXISTS idx_sequence_warming_up_sequence_id
    ON sequence_warming_up(sequence_id, sort_order);

CREATE TABLE IF NOT EXISTS sun_salutation_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ja VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sun_salutation_master_name_ja UNIQUE (name_ja)
);

CREATE TABLE IF NOT EXISTS sequence_sun_salutation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL,
    sun_salutation_master_id BIGINT,
    custom_name VARCHAR(255),
    sort_order INTEGER NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sequence_sun_salutation_sequence
        FOREIGN KEY (sequence_id) REFERENCES sequences(id),
    CONSTRAINT fk_sequence_sun_salutation_master
        FOREIGN KEY (sun_salutation_master_id) REFERENCES sun_salutation_master(id),
    CONSTRAINT chk_sequence_sun_salutation_source
        CHECK (
            (sun_salutation_master_id IS NOT NULL AND custom_name IS NULL)
            OR (sun_salutation_master_id IS NULL AND custom_name IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_sun_salutation_master_display_order
    ON sun_salutation_master(display_order, id);

CREATE INDEX IF NOT EXISTS idx_sequence_sun_salutation_sequence_id
    ON sequence_sun_salutation(sequence_id, sort_order);

CREATE TABLE IF NOT EXISTS peak_pose_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ja VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_peak_pose_master_name_ja UNIQUE (name_ja)
);

CREATE TABLE IF NOT EXISTS sequence_peak_pose (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL,
    peak_pose_master_id BIGINT,
    custom_name VARCHAR(255),
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sequence_peak_pose_sequence
        FOREIGN KEY (sequence_id) REFERENCES sequences(id),
    CONSTRAINT fk_sequence_peak_pose_master
        FOREIGN KEY (peak_pose_master_id) REFERENCES peak_pose_master(id),
    CONSTRAINT chk_sequence_peak_pose_source
        CHECK (
            (peak_pose_master_id IS NOT NULL AND custom_name IS NULL)
            OR (peak_pose_master_id IS NULL AND custom_name IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_peak_pose_master_display_order
    ON peak_pose_master(display_order, id);

CREATE INDEX IF NOT EXISTS idx_sequence_peak_pose_sequence_id
    ON sequence_peak_pose(sequence_id, sort_order);
