CREATE TABLE IF NOT EXISTS sequences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_minutes INTEGER NOT NULL,
    level INTEGER NOT NULL,
    peak_pose_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    peak_pose_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS breathing_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_breathing_master_name_category UNIQUE (name, category)
);

CREATE TABLE IF NOT EXISTS sequence_breathing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sequence_id BIGINT NOT NULL,
    breathing_master_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sequence_breathing_sequence
        FOREIGN KEY (sequence_id) REFERENCES sequences(id),
    CONSTRAINT fk_sequence_breathing_master
        FOREIGN KEY (breathing_master_id) REFERENCES breathing_master(id)
);

CREATE INDEX IF NOT EXISTS idx_sequence_breathing_sequence_id
    ON sequence_breathing(sequence_id, display_order);
